In [3]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [4]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [5]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [6]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [7]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


In [8]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


In [9]:
a == 1

True

In [10]:
h = (a==1)
print(h)
type(h)

True


bool

In [11]:
h = (a==2)
print(h)
type(h)

False


bool

In [12]:
i = True
type(i)

bool

In [13]:
ii = 'True'
type(ii)

str

In [14]:
# Operação ==
a==b

True

In [15]:
# Operação ><
a>b

False

In [16]:
# Operação !=
a!=b

False

In [17]:
# Operação >= ou <=
a>=b

True

In [18]:
# Soma 
a+b

2.0

In [19]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [20]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [21]:
# Divisão
a/b

1.0

In [22]:
# Potencia
5**2

25

In [23]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [24]:
math.exp(0)

1.0

In [25]:
math.exp(a)

2.718281828459045

In [26]:
math.exp(-10)

4.5399929762484854e-05

In [27]:
import math as mt
mt.log(c)

0.0

In [28]:
mt.log10(100)

2.0

In [29]:
# Listas
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [30]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [31]:
myFirstList==a

False

In [32]:
myFirstList[0]==a

True

In [33]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [34]:
type(mySecList)

list

In [35]:
type(mySecList[2])


str

In [36]:
type(mySecList[1])

int

In [37]:
#CAMINHOS PATH
path = r"C:\Users\pbeal\OneDrive\Documentos\GitHub\ENS5172_20241"
print(path)

C:\Users\pbeal\OneDrive\Documentos\GitHub\ENS5172_20241


In [40]:
path = "C:/Users/pbeal/OneDrive/Documentos/GitHub/ENS5172_20241"
print(path)

C:/Users/pbeal/OneDrive/Documentos/GitHub/ENS5172_20241


In [41]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01-checkpoint.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'venv']

In [42]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [43]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/pbeal/OneDrive/Documentos/GitHub/ENS5172_20241/.git'

In [44]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [45]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\pbeal\\OneDrive\\Documentos\\GitHub\\ENS5172_20241\\venv\\Scripts'

In [50]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\pbeal\\Documents\\')

In [51]:
os.getcwd()

'C:\\Users\\pbeal\\Documents'

In [52]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\pbeal\Documents/test


In [53]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\pbeal\Documents/test2


In [54]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [55]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [56]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.31739279 0.49571038 0.60080968 0.06945515 0.39197517 0.71637001
  0.24024939 0.42575724 0.66860201 0.41944317]
 [0.95149997 0.39144281 0.61071049 0.27449937 0.0585458  0.04774589
  0.24867916 0.36868495 0.24464959 0.27894265]
 [0.20602377 0.52340763 0.91181033 0.61264306 0.57195389 0.38434464
  0.25507312 0.33871    0.11211156 0.79040753]
 [0.5376364  0.9785032  0.48455756 0.27011229 0.01511017 0.29162265
  0.61131138 0.4343945  0.98278623 0.22183664]
 [0.93728761 0.50969325 0.20850737 0.47487986 0.41206207 0.72072888
  0.4310619  0.37724177 0.7090019  0.7600391 ]
 [0.61245784 0.06803844 0.2337285  0.28419326 0.05565807 0.27681851
  0.52862572 0.59221249 0.26995648 0.96976409]
 [0.29347791 0.96435634 0.95032581 0.60197833 0.91994206 0.80143797
  0.90402534 0.94724775 0.07413409 0.78740784]
 [0.72346851 0.56130205 0.31889378 0.12596429 0.89143682 0.63436259
  0.96654457 0.05777772 0.19704067 0.82794208]
 [0.48567967 0.48540832 0.7846493  0.6882987  0.50067921 0.29173144
  0.05076178

In [57]:
# Acessando valores da matriz
n[0,:]

array([0.31739279, 0.49571038, 0.60080968, 0.06945515, 0.39197517,
       0.71637001, 0.24024939, 0.42575724, 0.66860201, 0.41944317])

In [58]:
n[:,0]

array([0.31739279, 0.95149997, 0.20602377, 0.5376364 , 0.93728761,
       0.61245784, 0.29347791, 0.72346851, 0.48567967, 0.53910212])

In [59]:
n[:,1:5]

array([[0.49571038, 0.60080968, 0.06945515, 0.39197517],
       [0.39144281, 0.61071049, 0.27449937, 0.0585458 ],
       [0.52340763, 0.91181033, 0.61264306, 0.57195389],
       [0.9785032 , 0.48455756, 0.27011229, 0.01511017],
       [0.50969325, 0.20850737, 0.47487986, 0.41206207],
       [0.06803844, 0.2337285 , 0.28419326, 0.05565807],
       [0.96435634, 0.95032581, 0.60197833, 0.91994206],
       [0.56130205, 0.31889378, 0.12596429, 0.89143682],
       [0.48540832, 0.7846493 , 0.6882987 , 0.50067921],
       [0.68620232, 0.13807521, 0.93243483, 0.65102311]])

In [60]:
n[0,1:5]

array([0.49571038, 0.60080968, 0.06945515, 0.39197517])

In [61]:
n[0,-1]

0.41944316701541484

In [62]:
n[0,4:-1]

array([0.39197517, 0.71637001, 0.24024939, 0.42575724, 0.66860201])

In [63]:
n[0,4:]

array([0.39197517, 0.71637001, 0.24024939, 0.42575724, 0.66860201,
       0.41944317])

In [64]:
an = np.log(n*5)
print(an)

[[ 0.46182274  0.90767449  1.09996085 -1.05763609  0.67288112  1.27587944
   0.18336016  0.75555195  1.20687161  0.74061067]
 [ 1.55972229  0.67152206  1.11630565  0.3166316  -1.22850802 -1.43242437
   0.21784617  0.61162512  0.20150959  0.33268884]
 [ 0.0296742   0.9620432   1.51711463  1.11946511  1.05074101  0.65322227
   0.24323287  0.52682692 -0.57882296  1.37423131]
 [ 0.98886513  1.58770669  0.88491887  0.3005204  -2.58294902  0.37714331
   1.11728908  0.77563575  1.59207427  0.10362391]
 [ 1.54467282  0.93549171  0.04165703  0.86474449  0.72285662  1.28194567
   0.76793433  0.63456891  1.26554085  1.33505251]
 [ 1.11916275 -1.07824449  0.15584281  0.35133713 -1.27909024  0.32504471
   0.97196329  1.08554814  0.29994339  1.57873546]
 [ 0.383485    1.5731435   1.55848751  1.10190408  1.52599333  1.38809021
   1.50854003  1.55524331 -0.99244193  1.37042897]
 [ 1.28573965  1.03194181  0.46654071 -0.46231889  1.4945172   1.15430334
   1.57541004 -1.24171406 -0.01490722  1.42062583]
